export default [
    {
        id:'aa',
        title: "Концерт Depeche Mode",
        description: "Описание концерта здесь Depeche Mode. Описание концерта здесь Depeche Mode",
        price: 300,
        type: "concert",
    },
    {
        id:'bb',
        title: "Выставка Модильяни",
        description: "Описание выставки здесь выставка Модильяни. Описание выставки здесь выставка Модильяни",
        price: 200,
        type: "exhibition",
    },
    {
        id:'cc',
        title: "Концерт Руки Вверх",
        description: "Описание концерта Руки Вверх. Описание концерта Руки Вверх",
        price: 500,
        type: "concert",
    },
    {
        id:'dd',
        title: "Выставка Пикассо",
        description: "Описание выставки здесь Пикассо. Описание выставки здесь Пикассо",
        price: 100,
        type: "exhibition",
    },
    {
        id:'ee',
        title: "Голубая камея",
        description: "Описание Голубая камея. Описание Голубая камея.",
        price: 550,
        type: "theater",
    },
    {
        id:'ff',
        title: "Преступление и наказание",
        description: "Описание Преступление и наказание. Описание Преступление и наказание",
        price: 750,
        type: "theater",
    },
    {
        id:'gg',
        title: "Дюймовочка и принц",
        description: "Описание Дюймовочка и принц. Описание Дюймовочка и принц",
        price: 600,
        type: "theater",
    },
]